"""
Orchestrator — build the engine, then predict.

    python run_engine.py --build                       # full rebuild, both tours
    python run_engine.py --build --tours atp           # ATP only
    python run_engine.py --build --skip-conditions     # reuse existing conditions
    python run_engine.py --a "Alcaraz" --b "Sinner" --surface Clay --best-of 5
    python run_engine.py --status                      # what is built, how fresh

Build order matters: ratings and serve/return both read the raw match log
independently, but conditions needs the long-form explode and matchups needs the
completed-match filter, so everything is driven from data/raw/matches_{tour}.parquet
and nothing depends on another processed table. That means any step can be skipped
and re-run on its own.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from engine import conditions, matchups, ratings, serve_return  # noqa: E402
from engine.predict import Engine, _print_prediction  # noqa: E402
from engine.schema import PROCESSED, RAW, SURFACES, TOURS  # noqa: E402

STEPS = [
    ("ratings", "ratings.parquet", "ratings_current.parquet"),
    ("serve_return", "serve_return.parquet", "serve_return_current.parquet"),
    ("conditions", "conditions.parquet", None),
    ("matchups", "h2h.parquet", None),
]


def build(tours: tuple[str, ...], skip: set[str]) -> None:
    t0 = time.time()
    print(f"Building engine for: {', '.join(t.upper() for t in tours)}")

    if "ratings" not in skip:
        print("\n[1/4] ratings")
        pm, cur = ratings.build_all(tours)
        pm.to_parquet(PROCESSED / "ratings.parquet", index=False)
        cur.to_parquet(PROCESSED / "ratings_current.parquet", index=False)

    if "serve_return" not in skip:
        print("\n[2/4] serve/return")
        pm, cur = serve_return.build_all(tours)
        pm.to_parquet(PROCESSED / "serve_return.parquet", index=False)
        cur.to_parquet(PROCESSED / "serve_return_current.parquet", index=False)

    if "conditions" not in skip:
        print("\n[3/4] conditions")
        conditions.build_all(tours).to_parquet(PROCESSED / "conditions.parquet", index=False)

    if "matchups" not in skip:
        print("\n[4/4] head-to-head")
        matchups.build_all(tours).to_parquet(PROCESSED / "h2h.parquet", index=False)

    print(f"\nBuild complete in {time.time()-t0:.1f}s")


def status() -> None:
    print(f"\nraw      {RAW}")
    if (RAW / "SYNTHETIC.marker").exists():
        print("  ** SYNTHETIC DATA — generated by tools/make_synthetic_data.py, "
              "not real results **")
    any_raw = False
    for tour in TOURS:
        p = RAW / f"matches_{tour}.parquet"
        if p.exists():
            any_raw = True
            m = pd.read_parquet(p, columns=["season", "tourney_date"])
            print(f"  matches_{tour}.parquet   {len(m):>8,} matches  "
                  f"{int(m['season'].min())}–{int(m['season'].max())}  "
                  f"latest {m['tourney_date'].max().date()}")
    if not any_raw:
        print("  (empty — run `python fetch_data.py`)")

    print(f"\nprocessed  {PROCESSED}")
    for _, primary, secondary in STEPS:
        for name in (primary, secondary):
            if not name:
                continue
            p = PROCESSED / name
            if p.exists():
                size = p.stat().st_size / 1e6
                age = (time.time() - p.stat().st_mtime) / 3600
                print(f"  {name:<32}{size:>8.1f} MB   {age:>6.1f}h old")
            else:
                print(f"  {name:<32}{'MISSING':>8}")
    print()


def main() -> None:
    ap = argparse.ArgumentParser(description="Build and run the tennis engine.")
    ap.add_argument("--build", action="store_true", help="rebuild processed tables")
    ap.add_argument("--status", action="store_true", help="show what is built")
    ap.add_argument("--tours", nargs="+", default=list(TOURS), choices=list(TOURS))
    for step, _, _ in STEPS:
        ap.add_argument(f"--skip-{step.replace('_','-')}", action="store_true")

    ap.add_argument("--a"); ap.add_argument("--b")
    ap.add_argument("--surface", default="Hard", choices=list(SURFACES))
    ap.add_argument("--tour", default="atp", choices=list(TOURS))
    ap.add_argument("--best-of", type=int, default=3, choices=[3, 5])
    ap.add_argument("--date", default=None)
    ap.add_argument("--tournament", default=None)
    args = ap.parse_args()

    if args.status:
        status()
        return

    if args.build:
        skip = {s for s, _, _ in STEPS if getattr(args, f"skip_{s}")}
        build(tuple(args.tours), skip)

    if args.a and args.b:
        eng = Engine(tuple(args.tours))
        _print_prediction(
            eng.predict(
                args.a, args.b, tour=args.tour, surface=args.surface,
                best_of=args.best_of, match_date=args.date, tournament=args.tournament,
            )
        )
    elif not args.build:
        ap.print_help()


if __name__ == "__main__":
    main()
